In [1]:
import numpy as np
import pandas as pd

### Operadores

In [2]:
def operadores(x_val, y_val):
    if y_val == 1 and x_val == 1:
        return 1
    elif y_val == 1 and x_val == 0:
        return -1
    else:
        return 0

### Definir dimensiones a utilizar

In [3]:
def valores_importantes(X, Y):
    x_filas, x_columnas = X.shape
    y_filas, y_columnas  = Y.shape

    valores = {
        'x_fil' : x_filas,
        'x_col' : x_columnas,
        'y_fil' : y_filas,
        'y_col' : y_columnas
    }
    return valores

### GENERAR MATRIZ M

In [4]:
def genera_M(m, n):
    return np.zeros((m,n))

### ENTRENAMIENTO

In [ ]:
def entrena(X, Y, m, n, muestras, matriz_M):
        
    # porcada muestra de X
    for k in range(muestras):
        # Recorrer valores y
        for j in range(m):
            # Recorrer todas las características X
            for i in range(n):
                x_val = X[k, i]
                y_val = Y[k, j]
                matriz_M[j, i] += operadores(x_val, y_val)
    
    matriz_entrenada = pd.DataFrame(matriz_M)
    matriz_entrenada = matriz_entrenada.values
    return matriz_entrenada

### Ejemplo

In [11]:
xs = pd.DataFrame([[1, 0, 1, 0, 1], 
                  [1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0]])

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

X = xs.values
Y = ys.values

valores = valores_importantes(X, Y)
m = valores['y_fil']
n = valores['x_col']
muestras = valores['x_fil']
M = genera_M(m, n)
matriz_M = M.copy()
matriz_entrenada = entrena(X, Y, m, n, muestras, matriz_M)
print('===================== EXPERIMENTO DE LA CLASE =====================')
print('\n--------- PATRONES DE ENTRADA --------- ')
print('>>> X')
print(X)
print('\n>>> Y')
print(Y)

print('\n--------- VALORES IMPORTANTES --------- ')
print(f'm: {m}')
print(f'n: {n}')

print('\n--------- MATRIZ M VACÍA --------- ')
print(M)

print('\n--------- MATRIZ ENTRENADA --------- ')
print(matriz_entrenada)

===================== EXPERIMENTO DE LA CLASE =====================

--------- PATRONES DE ENTRADA --------- 
>>> X
[[1 0 1 0 1]
 [1 1 0 0 1]
 [1 0 1 1 0]]

>>> Y
[[1 0 0]
 [0 1 0]
 [0 0 1]]

--------- VALORES IMPORTANTES --------- 
m: 3
n: 5

--------- MATRIZ M VACÍA --------- 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

--------- MATRIZ ENTRENADA --------- 
[[ 1. -1.  1. -1.  1.]
 [ 1.  1. -1. -1.  1.]
 [ 1. -1.  1.  1. -1.]]
