In [59]:
import numpy as np
import pandas as pd

### Operadores

In [71]:
def operadores(x_val, y_val):
    for x, y in zip(x_val, y_val):
        if y == 1 and x == 1:
            return 1
        elif y == 1 and x == 0:
            return -1
        else:
            return 0

### Definir dimensiones a utilizar

In [72]:
def valores_importantes(X, Y):
    n = X.shape[1]
    m = Y.shape[1]
    return n, m

### GENERAR MATRIZ M

In [62]:
def genera_M(m, n):
    return np.zeros((m,n))

### ENTRENAMIENTO

In [ ]:
def entrena (xs, ys):
    """
    Columna de ys contra filas de xs
    """
    pass

### Ejemplo

In [73]:
xs = pd.DataFrame([[1, 0, 1, 0, 1], 
                  [1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0]])

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]]).T

X = xs.values
Y = ys.values

n, m = valores_importantes(X, Y)
matriz_M = genera_M(m, n)

print('--------- PATRONES DE ENTRADA --------- ')
print('>>> X')
print(xs)
print('\n>>> Y')
print(ys)

print('\n--------- VALORES IMPORTANTES --------- ')
print(f'n: {n}')
print(f'm: {m}')

print('\n--------- MATRIZ M VACÍA --------- ')
print(matriz_M)

print('\n--------- ENTRENAMIENTO --------- ')


--------- PATRONES DE ENTRADA --------- 
>>> X
   0  1  2  3  4
0  1  0  1  0  1
1  1  1  0  0  1
2  1  0  1  1  0

>>> Y
   0  1  2
0  1  0  0
1  0  1  0
2  0  0  1

--------- VALORES IMPORTANTES --------- 
n: 5
m: 3

--------- MATRIZ M VACÍA --------- 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

--------- ENTRENAMIENTO --------- 


In [69]:
def entrena (xs, ys, matriz_M, m, n):
    """
    Columna de ys contra filas de xs
    """
    for i in range(m):
        iteracion = operadores(ys[i], xs[0])
    matriz_M += iteracion
    print(matriz_M)

entrena (xs, ys, matriz_M, m, n)

ValueError: operands could not be broadcast together with shapes (3,5) (3,) (3,5) 