In [29]:
import numpy as np
import pandas as pd

### Operadores

In [30]:
def operadores(x_val, y_val):
    res = []
    for x, y in zip(x_val, y_val):
        if y == 1 and y == 1:
            res.append(1)
        elif y == 1 and x == 0:
            res.append(-1)
        else:
            res.append(0)
    return res

### Definir dimensiones a utilizar

In [31]:
def valores_importantes(lista_df):
    n = lista_df[0].shape[0]
    m = len(lista_df[1])

    dfs = {}
    for idx, df in enumerate(lista_df):
        dfs[idx] = df

    return n, m


### GENERAR MATRIZ M

In [37]:
def genera_M(m, n):
    dim = (m, n)
    matriz =  np.zeros(dim)
    return matriz

In [36]:
dim = (3, 5)
matriz = np.zeros(dim)
matriz

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ejemplo

In [39]:
xs = pd.DataFrame([[1, 0, 1, 0, 1], 
                  [1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0]]).T

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]]).T

n, m = valores_importantes([xs, ys])
matriz_M = genera_M(m, n)

print('--------- PATRONES DE ENTRADA --------- ')
print('>>> X')
print(xs)
print('\n>>> Y')
print(ys)

print('\n--------- VALORES IMPORTANTES --------- ')
print(f'n: {n}')
print(f'm: {m}')

print('\n--------- MATRIZ M VACÍA --------- ')
print(matriz_M)

--------- PATRONES DE ENTRADA --------- 
>>> X
   0  1  2
0  1  1  1
1  0  1  0
2  1  0  1
3  0  0  1
4  1  1  0

>>> Y
   0  1  2
0  1  0  0
1  0  1  0
2  0  0  1

--------- VALORES IMPORTANTES --------- 
n: 5
m: 3

--------- MATRIZ M VACÍA --------- 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
