In [104]:
import numpy as np
import pandas as pd

### Operadores

In [105]:
def operadores(x_val, y_val):
    for x, y in zip(x_val, y_val):
        if y == 1 and x == 1:
            return 1
        elif y == 1 and x == 0:
            return -1
        else:
            return 0

### Definir dimensiones a utilizar

In [106]:
def valores_importantes(X, Y):
    x_filas, x_columnas = X.shape
    y_filas, y_columnas  = Y.shape

    valores = {
        'x_fil' : x_filas,
        'x_col' : x_columnas,
        'y_fil' : y_filas,
        'y_col' : y_columnas
    }
    return valores

In [107]:
xs = pd.DataFrame([[1, 0, 1, 0, 1], 
                  [1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0]])

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

X = xs.values
Y = ys.values
valores = valores_importantes(X, Y)
valores

{'x_fil': 3, 'x_col': 5, 'y_fil': 3, 'y_col': 3}

### GENERAR MATRIZ M

In [108]:
def genera_M(m, n):
    return np.zeros((m,n))

### ENTRENAMIENTO

In [ ]:
def entrena(m, n, muestras, matriz_M):

    muestras, n = X.shape
    m = Y.shape[1]
        
    # Recorrer todas las muestras
    for k in range(muestras):
        # Recorrer todas las salidas
        for j in range(m):
            # Recorrer todas las características
            for i in range(n):
                # Obtener los valores individuales
                x_val = X[k, i]
                y_val = Y[k, j]
                # Llamar a la función operadores y acumular
                matriz_M[j, i] += operadores(x_val, y_val)
    
    matriz_entrenada = pd.DataFrame(matriz_M, index=ys.columns, columns=xs.columns)
    return matriz_entrenada

### Ejemplo

In [110]:
xs = pd.DataFrame([[1, 0, 1, 0, 1], 
                  [1, 1, 0, 0, 1],
                  [1, 0, 1, 1, 0]])

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])

X = xs.values
Y = ys.values

valores = valores_importantes(X, Y)
m = valores['y_fil']
n = valores['x_col']
muestras = valores['x_fil']
matriz_M = genera_M(m, n)

print('--------- PATRONES DE ENTRADA --------- ')
print('>>> X')
print(X)
print('\n>>> Y')
print(Y)

print('\n--------- VALORES IMPORTANTES --------- ')
print(f'm: {m}')
print(f'n: {n}')

print('\n--------- MATRIZ M VACÍA --------- ')
print(matriz_M)

print('\n--------- ENTRENAMIENTO --------- ')
matriz_M = entrena(m, n, muestras, matriz_M)

--------- PATRONES DE ENTRADA --------- 
>>> X
[[1 0 1 0 1]
 [1 1 0 0 1]
 [1 0 1 1 0]]

>>> Y
[[1 0 0]
 [0 1 0]
 [0 0 1]]

--------- VALORES IMPORTANTES --------- 
m: 3
n: 5

--------- MATRIZ M VACÍA --------- 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

--------- ENTRENAMIENTO --------- 


TypeError: 'numpy.int64' object is not iterable

In [ ]:
def entrena(xs, ys):
    """
    Entrena la matriz M usando la función operadores() para cada combinación
    de muestra, salida y característica.
    """
    # Convertir a arrays de NumPy para facilitar el acceso
    X = xs.values   # shape (muestras, características)
    Y = ys.values   # shape (muestras, salidas)
    
    muestras, n = X.shape
    m = Y.shape[1]
    
    # Inicializar matriz de pesos con ceros
    M = np.zeros((m, n))
    
    # Recorrer todas las muestras
    for k in range(muestras):
        # Recorrer todas las salidas
        for j in range(m):
            # Recorrer todas las características
            for i in range(n):
                # Obtener los valores individuales
                x_val = X[k, i]
                y_val = Y[k, j]
                # Llamar a la función operadores y acumular
                M[j, i] += operadores(x_val, y_val)
    
    # Devolver como DataFrame con nombres de filas y columnas
    return pd.DataFrame(M, index=ys.columns, columns=xs.columns)

In [ ]:
def entrena(xs, ys):
    """
    Entrena la matriz de pesos M usando la regla:
    +1 si y==1 y x==1
    -1 si y==1 y x==0
     0 en otro caso
    Acumulando sobre todas las muestras.
    
    Parámetros:
    xs : DataFrame de pandas con shape (muestras, características)
    ys : DataFrame de pandas con shape (muestras, salidas)
    
    Retorna:
    M : DataFrame con shape (salidas, características)
    """
    # Convertir a arrays de NumPy
    X = xs.values
    Y = ys.values
    
    # Número de salidas (m) y características (n)
    m = Y.shape[1]
    n = X.shape[1]
    
    # Expandir dimensiones para broadcasting:
    # Y_exp: (muestras, salidas, 1)
    # X_exp: (muestras, 1, características)
    Y_exp = Y[:, :, np.newaxis]
    X_exp = X[:, np.newaxis, :]
    
    # Calcular condiciones
    cond1 = (Y_exp == 1) & (X_exp == 1)   # +1
    cond2 = (Y_exp == 1) & (X_exp == 0)   # -1
    
    # Sumar sobre las muestras (eje 0)
    M = np.sum(cond1, axis=0) - np.sum(cond2, axis=0)
    
    # Devolver como DataFrame con índices adecuados
    return pd.DataFrame(M, index=ys.columns, columns=xs.columns)

In [ ]:
# Ejemplo con tus datos (ys sin transponer, como matriz de muestras × salidas)
xs = pd.DataFrame([[1, 0, 1, 0, 1],
                   [1, 1, 0, 0, 1],
                   [1, 0, 1, 1, 0]])

ys = pd.DataFrame([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])   # shape (3,3)

M_entrenada = entrena(xs, ys)
print(M_entrenada)

   0  1  2  3  4
0  1 -1  1 -1  1
1  1  1 -1 -1  1
2  1 -1  1  1 -1
